import React from 'react';

export default class PCProduct extends React.Component {
  render() {
    return (
      <div className="clearfix rmd_pro_list">
        <ul id="rmd_pro_list">
          <li><a href="http://photo.163.com/" jcid={5551}>相册</a></li><li><a href="http://gzy.mail.163.com/?from=163product" jcid={5552}>公正邮</a></li><li><a href="http://yxp.163.com/" jcid={5553}>印像派</a></li><li><a href="http://rd.da.netease.com/redirect?t=VGa7BN&p=ve4u5l&proId=1024&target=http%3A%2F%2Fwww.kaola.com%2F%3Ftag%3Dbe3d8d027a530881037ef01d304eb505" jcid={5554}>考拉海购</a></li><li><a href="http://open.163.com/" jcid={5555}>公开课</a></li><li><a href="http://i.money.163.com/?imb1" jcid={5556}>财经客户端</a></li><li><a href="https://pop.lmlc.com/web/activity/practiceGold/index.html?from=tgn163productlist2" jcid={5557}>赚钱</a></li><li><a href="http://yuedu.163.com" jcid={5558}>云阅读</a></li><li><a href="http://fanyi.youdao.com/?vendor=163homepage" jcid={5559}>翻译</a></li><li><a href="http://love.163.com/?from=wscp" jcid="555A">花田</a></li><li><a href="http://study.163.com/?utm_source=163.com&utm_medium=web_productlist&utm_campaign=business" jcid="555B">云课堂</a></li><li><a href="http://mall.163.com/?from=mmwww" jcid="555C">商城</a></li><li><a href="http://888.163.com/?from=tgnh2" jcid="555D">1元购</a></li><li><a href="http://trip.163.com/" jcid="555E">火车票</a></li><li><a href="http://www.163.com/newsapp/" jcid="555F">新闻客户端</a></li><li><a href="http://www.weiyang.cn/" jcid="555G">网易味央</a></li><li><a href="http://manhua.163.com/" jcid="555H">漫画</a></li><li><a href="http://www.icourse163.org/?utm_source=163.com&utm_medium=web_productlist&utm_campaign=business" jcid="555I">大学MOOC</a></li><li><a href="http://qian.163.com/" jcid="555J">有钱</a></li><li><a href="http://you.163.com?from=web_in_wyshouye" jcid="555K">严选</a></li><li><a href="http://note.youdao.com/?vendor=163index" jcid="555L">云笔记</a></li><li><a href="http://cc.163.com/" jcid="555M">CC语音</a></li><li><a href="http://tie.163.com/" jcid="555N">跟贴</a></li><li><a href="http://caipiao.163.com/#from=www" jcid="555O">彩票</a></li><li><a href="https://3c.163.com/?from=wangyimenhu19" jcid="555P">网易智造</a></li><li><a href="http://y.163.com/download/index?from=wscp" jcid="555Q">美聊</a></li><li><a href="http://www.lofter.com/?act=qb163rk_20141031_12" jcid="555R">LOFTER</a></li><li><a href="http://cidian.youdao.com/" jcid="555S">有道词典</a></li><li><a href="http://fa.163.com/?from=tgn163cp" jcid="555T">贵金属</a></li><li><a href="https://zc.163.com?utm_source=newspc&utm_medium=home_pc&utm_campaign=Crowdfunding&mmd=newspc&mpl=home_pc&mkw=Crowdfunding" jcid="555U">众筹</a></li><li><a href="http://x.163.com?source=163webproduct" jcid="555V">青果</a></li><li><a href="http://www.bobo.com/" jcid="555W">BoBo直播</a></li><li><a href="http://baoxian.163.com/?from=wycp" jcid="555X">车险</a></li><li><a href="http://blog.163.com/?fromService" jcid="555Y">博客</a></li><li><a href="https://i.epay.126.net/a/8a/static/188activity.html?utm_source=163&utm_medium=recommend_pc&utm_campaign=1888cashfest&mmd=163&mpl=recommend_pc&mkw=1888cashfest" jcid="555Z">理财</a></li><li><a href="http://yuehui.163.com/?from=wscp" jcid="555a">同城约会</a></li></ul>
      </div>
    );
  }
};